AMZN_CATEGORIES = [
    'Clothing',
    'Shoes',
    'Accessories',
    'Jewelry',
    'Watches',
    'Handbags & Wallets',
    'Luggage & Travel Gear',
    'Activewear',
    'Sleep & Lounge',
    'Swim',
    'Tops',
    'Bottoms',
    'Dresses',
    'Suits & Sport Coats',
    'Outerwear',
    'Underwear',
    'Socks & Hosiery',
    'Shirts',
    'Pants',
    'Shorts',
    'Sweaters',
    'Hoodies & Sweatshirts',
    'Jackets & Coats',
    'Jeans',
    'Leggings',
    'Skirts',
    'Lingerie',
    'Bras',
    'Panties',
    'Shapewear',
    'Maternity',
    'Nursing',
    'Uniforms, Work & Safety',
    'Costumes & Cosplay Apparel',
    'Wedding & Engagement',
    'Fine Jewelry',
    'Fashion Jewelry',
    'Body Jewelry',
    'Men',
    'Women',
    'Girls',
    'Boys',
    'Baby',
    'Boots',
    'Sneakers',
    'Sandals',
    'Slippers',
    'Athletic',
    'Outdoor',
    'Loafers & Slip-Ons',
    'Oxfords',
    'Flats',
    'Heels',
    'Belts',
    'Hats & Caps',
    'Scarves & Wraps',
    'Sunglasses & Eyewear Accessories',
    'Gloves & Mittens',
    'Wallets, Card Cases & Money Organizers',
    'Ties, Cummerbunds & Pocket Squares',
    'Cufflinks, Shirt Studs & Tie Clips',
    'Earrings',
    'Necklaces',
    'Bracelets',
    'Rings',
    'Charms & Charm Bracelets',
    'Pendants',
    'Brooches & Pins',
    'Wrist Watches',
    'Pocket Watches',
    'Watch Bands',
    'Watch Accessories',
    'Shoulder Bags',
    'Totes',
    'Satchels',
    'Crossbody Bags',
    'Clutches & Evening Bags',
    'Backpacks',
    'Messenger Bags',
    'Luggage',
    'Travel Accessories',
    'Handbag Accessories',
    'Shoe Care & Accessories',
    'Sports & Fitness',
    'Outdoor Recreation',
    'Fan Shop',
    'Sports Equipment'
]
